trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository'

stages:
- stage: Build
  jobs:
  - job: BuildJava
    steps:
    - task: Cache@2
      inputs:
        key: 'maven | "$(Agent.OS)" | vesta-api/pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
        path: $(Pipeline.Workspace)/.m2/repository

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      inputs:
        mavenPomFile: 'vesta-api/pom.xml'
        goals: 'clean package -DskipTests'
        options: '$(MAVEN_OPTS)'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'vesta-api/target'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'